theme: jekyll-theme-minimal
title: --------------------------
subtitle: Raúl Figueroa Sierra
description: r.figueroa@uniandes.edu.co
show_downloads: FALSE
logo: /docs/foto.JPG
google_site_verification: "qO0ypQFjMAJu3kmyFYH_uAHSR7KUPr6s4WiyZeX33xQ"
plugins:
  - jekyll-sitemap

